ALTER TABLE public.spreadsheet_orders
  ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE OR REPLACE FUNCTION public.create_public_mentoring_booking(
    p_owner_user_id UUID DEFAULT NULL,
    p_client_name TEXT DEFAULT NULL,
    p_title TEXT DEFAULT NULL,
    p_email TEXT DEFAULT NULL,
    p_date DATE DEFAULT NULL,
    p_time TEXT DEFAULT NULL,
    p_whatsapp TEXT DEFAULT NULL,
    p_form_details JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_owner_id UUID;
    v_appointment public.appointments%ROWTYPE;
    v_order public.spreadsheet_orders%ROWTYPE;
BEGIN
    IF p_owner_user_id IS NOT NULL AND EXISTS (
      SELECT 1 FROM public.profiles WHERE id = p_owner_user_id
    ) THEN
      v_owner_id := p_owner_user_id;
    ELSE
      SELECT id
      INTO v_owner_id
      FROM public.profiles
      ORDER BY created_at ASC
      LIMIT 1;
    END IF;

    IF v_owner_id IS NULL THEN
      RAISE EXCEPTION 'Public mentoring booking owner profile was not found';
    END IF;

    IF NULLIF(TRIM(COALESCE(p_client_name, '')), '') IS NULL THEN
      RAISE EXCEPTION 'Client name is required';
    END IF;

    IF NULLIF(TRIM(COALESCE(p_title, '')), '') IS NULL THEN
      RAISE EXCEPTION 'Mentoring title is required';
    END IF;

    IF p_date IS NULL THEN
      RAISE EXCEPTION 'Mentoring date is required';
    END IF;

    IF NULLIF(TRIM(COALESCE(p_time, '')), '') IS NULL THEN
      RAISE EXCEPTION 'Mentoring time is required';
    END IF;

    INSERT INTO public.appointments (
      user_id,
      client_name,
      title,
      email,
      whatsapp,
      form_details,
      date,
      time,
      status
    )
    VALUES (
      v_owner_id,
      TRIM(p_client_name),
      TRIM(p_title),
      NULLIF(TRIM(COALESCE(p_email, '')), ''),
      NULLIF(TRIM(COALESCE(p_whatsapp, '')), ''),
      COALESCE(p_form_details, '{}'::jsonb) || jsonb_build_object('source', 'public-1on1-mentoring-form'),
      p_date,
      TRIM(p_time),
      'confirmed'
    )
    RETURNING * INTO v_appointment;

    INSERT INTO public.spreadsheet_orders (
      user_id,
      customer_name,
      order_name,
      order_type,
      budget,
      status,
      due_date,
      meta
    )
    VALUES (
      v_owner_id,
      TRIM(p_client_name),
      TRIM(p_title),
      '1:1 Mentoring Session',
      0,
      'new',
      p_date,
      jsonb_build_object(
        'source', 'public-1on1-mentoring-form',
        'appointmentId', v_appointment.id,
        'formDetails', COALESCE(p_form_details, '{}'::jsonb) || jsonb_build_object(
          'clientName', TRIM(p_client_name),
          'email', NULLIF(TRIM(COALESCE(p_email, '')), ''),
          'whatsapp', NULLIF(TRIM(COALESCE(p_whatsapp, '')), ''),
          'title', TRIM(p_title),
          'date', p_date,
          'time', TRIM(p_time)
        ),
        'sessionLogs', jsonb_build_array(
          jsonb_build_object(
            'id', CONCAT('mentoring-intake-', v_appointment.id::text),
            'sessionDate', p_date,
            'topic', TRIM(p_title),
            'summary', CONCAT(
              'Kondisi awal: ', COALESCE(NULLIF(TRIM(COALESCE(p_form_details->>'mentoringNeed', '')), ''), '-'),
              E'\n',
              'Target hasil: ', COALESCE(NULLIF(TRIM(COALESCE(p_form_details->>'mentoringGoal', '')), ''), '-'),
              E'\n',
              'Catatan ini dibuat otomatis dari form booking mentoring.'
            ),
            'actionItems', '',
            'nextStep', 'Lakukan review kebutuhan client dan jadwalkan sesi mentoring pertama.',
            'progressPercent', 10,
            'updatedBy', TRIM(p_client_name),
            'createdAt', timezone('utc'::text, now()),
            'isAutoGenerated', true
          )
        ),
        'session', jsonb_build_object(
          'date', p_date,
          'time', TRIM(p_time)
        )
      )
    )
    RETURNING * INTO v_order;

    INSERT INTO public.spreadsheet_order_timeline (order_id, title, note, progress_percent, updated_by)
    VALUES
      (v_order.id, 'Booking Terkonfirmasi', 'Reservasi mentoring sudah tercatat dan siap dijadwalkan.', 10, 'system'),
      (v_order.id, 'Konteks & Objective Review', 'Review kebutuhan client dan siapkan objective sesi mentoring.', 25, 'system');

    RETURN jsonb_build_object(
      'appointment', to_jsonb(v_appointment),
      'order', to_jsonb(v_order)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.create_public_mentoring_booking(UUID, TEXT, TEXT, TEXT, DATE, TEXT, TEXT, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_public_mentoring_booking(UUID, TEXT, TEXT, TEXT, DATE, TEXT, TEXT, JSONB) TO anon, authenticated;
